# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HBS New Venture Competition' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HBS New Venture Competition

    # Database
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod 'Firebase/Storage'
    pod 'Firebase/Auth'
    
    # UI
    pod 'FasterVerificationCode'
    pod 'SVProgressHUD'
    pod 'PopupDialog', '~> 0.8'
    pod 'Cosmos', '~> 17.0'
    pod 'ESPullToRefresh'

end
